remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [A RandomForestClassifier for Recipe Ratings]
description: [a collaborative effort with Wan-Rong (Emma) Leung and Camille Sicat]